'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CinemaBookingEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CinemaBookingEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property Categories() As DbSet(Of Category)
    Public Property Cinemas() As DbSet(Of Cinema)
    Public Property Languages() As DbSet(Of Language)
    Public Property Movies() As DbSet(Of Movie)
    Public Property MovieCategories() As DbSet(Of MovieCategory)
    Public Property People() As DbSet(Of Person)
    Public Property Roles() As DbSet(Of Role)
    Public Property TheatreRooms() As DbSet(Of TheatreRoom)
    Public Property Users() As DbSet(Of User)

End Class
