'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Movie
    Public Property idmovie As Integer
    Public Property title As String
    Public Property plot As String
    Public Property length As Nullable(Of Short)
    Public Property iddirector As Nullable(Of Integer)
    Public Property idwriter As Nullable(Of Integer)
    Public Property release_year As Nullable(Of Date)
    Public Property idlanguage As Nullable(Of Integer)
    Public Property rating As Nullable(Of Byte)
    Public Property cover As Byte()

    Public Overridable Property Language As Language
    Public Overridable Property Person As Person
    Public Overridable Property Person1 As Person

End Class
