'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovieCategory
    Public Property idmovie_category As Integer
    Public Property idmovie As Integer
    Public Property idcategory As Integer
    Public Property desc As String

End Class
