'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Person
    Public Property idperson As Integer
    Public Property name As String
    Public Property surname As String
    Public Property birthdate As Nullable(Of Date)
    Public Property gender As String
    Public Property address As String
    Public Property email As String
    Public Property update_date As Nullable(Of Date)
    Public Property insertion_date As Nullable(Of Date)

    Public Overridable Property Movies As ICollection(Of Movie) = New HashSet(Of Movie)
    Public Overridable Property Movies1 As ICollection(Of Movie) = New HashSet(Of Movie)

End Class
