'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TheatreRoom
    Public Property idtheatre_room As Integer
    Public Property idmovie As Nullable(Of Integer)
    Public Property name As String
    Public Property desc As String
    Public Property rows_nr As Nullable(Of Integer)
    Public Property seats_per_row As Nullable(Of Integer)
    Public Property idcinema As Nullable(Of Integer)

End Class
