'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class User
    Public Property iduser As Integer
    Public Property idperson As Nullable(Of Integer)
    Public Property username As String
    Public Property password As String
    Public Property isactive As Nullable(Of Boolean)
    Public Property update_date As Nullable(Of Date)
    Public Property insertion_date As Nullable(Of Date)
    Public Property role As String

End Class
